### ISSUE TITLE
first mvn build results in an error, but the next steps seem to work for the first java action

### ISSUE THREAD

**Issue by JimTyrrell** [redhat-developer-demos/faas-java-tutorial#3]
mvn archetype:generate \
>   -DarchetypeGroupId=org.apache.openwhisk.java \
>   -DarchetypeArtifactId=java-action-archetype \
>   -DarchetypeVersion=1.0-SNAPSHOT \
>   -DgroupId=com.example \
>   -DartifactId=hello-openwhisk
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Maven Stub Project (No POM) 1
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] >>> maven-archetype-plugin:3.0.1:generate (default-cli) > generate-sources @ standalone-pom >>>
[INFO] 
[INFO] <<< maven-archetype-plugin:3.0.1:generate (default-cli) < generate-sources @ standalone-pom <<<
[INFO] 
[INFO] --- maven-archetype-plugin:3.0.1:generate (default-cli) @ standalone-pom ---
[INFO] Generating project in Interactive mode
[INFO] Archetype repository not defined. Using the one from [org.apache.openwhisk.java:java-action-archetype:1.0-SNAPSHOT] found in catalog local
[INFO] Using property: groupId = com.example
[INFO] Using property: artifactId = hello-openwhisk
Define value for property 'version' 1.0-SNAPSHOT: : 
[INFO] Using property: package = com.example
Confirm properties configuration:
groupId: com.example
artifactId: hello-openwhisk
version: 1.0-SNAPSHOT
package: com.example
 Y: : 
[INFO] ----------------------------------------------------------------------------
[INFO] Using following parameters for creating project from Old (1.x) Archetype: java-action-archetype:1.0-SNAPSHOT
[INFO] ----------------------------------------------------------------------------
[INFO] Parameter: basedir, Value: /Users/jimtyrrell/OpenWhisk/faas-java-tutorial
[INFO] Parameter: package, Value: com.example
[INFO] Parameter: groupId, Value: com.example
[INFO] Parameter: artifactId, Value: hello-openwhisk
[INFO] Parameter: packageName, Value: com.example
[INFO] Parameter: version, Value: 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 9.709 s
[INFO] Finished at: 2018-04-05T09:35:35-06:00
[INFO] Final Memory: 15M/223M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:3.0.1:generate (default-cli) on project standalone-pom: Directory hello-openwhisk already exists - please run from a clean directory -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by rafabene** [comment]
This is fixed at https://github.com/redhat-developer-demos/faas-java-tutorial/pull/2

**Comment by JimTyrrell** [comment]
We can close this then and the other issue
