### ISSUE TITLE
When creating the splitter, uppercase, and third step

### ISSUE THREAD

**Issue by JimTyrrell** [redhat-developer-demos/faas-java-tutorial#5]
Please call out the explicit FunctionApp.java you are wanting us to update.  It isn't clear at all as to which one you should be updating.

**Comment by kameshsampath** [comment]
@JimTyrrell - things are  fixed with @rafabene  PR which is merged now. please check and let us know

**Comment by rafabene** [comment]
I'll close this issue. If you think it needs an improvement, please reopen.

**Comment by JimTyrrell** [comment]
Yeap, this is much better by including this block of instructions in each of those sections:

The key was the cd splinter.  Nice work!!!

cd splitter
mvn clean package
wsk -i action update redhat-developers-demo/splitter target/splitter.jar --main com.example.FunctionApp
